# Docs at https://prettier.io/docs/en/options.html

semi: false
useTabs: false
tabWidth: 2
printWidth: 100
singleQuote: true
trailingComma: none
bracketSpacing: true
jsxBracketSameLine: false
arrowParens: avoid
endofline: lf
