language: node_js
node_js: stable

cache:
  yarn: true
  directories:
    - node_modules

script: yarn build

after_script:
  - cd ./site
  - git init
  - git config user.name "ntnyq"
  - git config user.email "ntnyq13@gmail.com"
  - git add .
  - git commit -m ":rocket:Update"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

branches:
  only:
    - master

env:
 global:
   - GH_REF: github.com/ntnyq/fe-life.git
