overrides:
  esbuild: ^0.27.2
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
peerDependencyRules:
  ignoreMissing:
    - '@algolia/client-search'
    - '@types/react'
    - react
    - react-dom
