packages:
  - .

overrides:
  esbuild: ^0.25.4

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

peerDependencyRules:
  ignoreMissing:
    - '@algolia/client-search'
    - '@types/react'
    - react
    - react-dom
